# Generated by Django 5.0.6 on 2024-07-18 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_dt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_name',
            field=models.CharField(default='default_order_name', max_length=255),
        ),
    ]
